
    
post_show:
    path:  /{id}/show
    defaults: { _controller: "ShopManagementBundle:Post:show" }

post_new:
    path:  /new
    defaults: { _controller: "ShopManagementBundle:Post:new" }

post_edits:
    path:  /{id}/edits
    defaults: { _controller: "ShopManagementBundle:Post:edits" }


post_creates:
    path:  /creates
    defaults: { _controller: "ShopManagementBundle:Post:creates" }

    
post_updates:
    path:  /{id}/updates
    defaults: { _controller: "ShopManagementBundle:Post:updates" }
    requirements: { _method: post|put }


post_deletes:
    path:  /{id}/deletes
    defaults: { _controller: "ShopManagementBundle:Post:deletes" }
    requirements: { _method: post|delete }
    
    
################################    
    
post_bought:
    path:  /{post_id}/bought
    defaults: { _controller: "ShopManagementBundle:Post:bought" }
    requirements: { _method: post|delete }


################################

get_posts:
    path:  /{shop_id}/posts/
    defaults: { _controller: "ShopManagementBundle:Shop:displayPosts" }
    
get_my_shop:
    path: /my_shop/
    defaults: {_controller: "ShopManagementBundle:MyShop:displayMyShop"}

get_shop:
    path: /shop/{shop_id}/
    defaults: {_controller: "ShopManagementBundle:Shop:displayShop"}
    
    

    
################################

image_uploads:
    path:  /image_uploads
    defaults: { _controller: ShopManagementBundle:Image:uploads}
    requirements: { _method: post|put }
    
    
image_deletes:
    path:  /image_deletes
    defaults: { _controller: ShopManagementBundle:Image:deletes}
    requirements: { _method: post|delete }
 
    
################################   

show_shop:
    path:  /{shop_id}/external
    defaults: { _controller: "ShopManagementBundle:External:showShop" }
    

################################

show_category:
    path: /category
    defaults: {_controller : "ShopManagementBundle:Category:getArticlesOfCategory"}
    

page_of_show_category:
  path: /page_of_category/{category_id}/
  defaults: {_controller: ShopManagementBundle:Category:getPageOfArticlesOfCategory}    
  

    
################################    
    
post_retweet:
    path:  /{post_id}/retweet
    defaults: { _controller: "ShopManagementBundle:Post:retweet" }
    requirements: { _method: post|delete }

