imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
      handler_id: ~
     #handler_id: session.handler.pdo # old configuration that caused the unexpected logout 
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form_themes: [ 'ShopManagementBundle:Form:form_errors.html.twig' ]


# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    #spool:     { type: memory }
    #delivery_address: adib.aroui@hotmail.fr


fos_user:
  db_driver: orm
  firewall_name: main
  from_email:
              address: "team@jou.la"
              sender_name: "No Reply"
  user_class: Members\Bundle\ManagementBundle\Entity\User
  profile:
        form:
            type:               members_management_user_profile
  registration:
        confirmation:
            enabled:    true
            from_email:
                address:        registration@jou.la
                sender_name:    Confirming Registration at Joula
            template: MembersManagementBundle:Registration:email.txt.twig
  resetting:
        email:
            from_email:
                address:        resetting@jou.la
                sender_name:    Resetting your account at Joula
            template: MembersManagementBundle:Resetting:email.txt.twig
  service:
        mailer: fos_user.mailer.twig_swift



liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_filter:
            quality:              50
            jpeg_quality:         50
            png_compression_level: 9
            png_compression_filter: ~
            format:               ~
            filters:
                relative_resize: { widen: 960 }
            post_processors:
                jpegoptim: { max: 50 }
              

    

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

