imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug


fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            client: default
            types:
                post:
                    properties:
                        postTitle: ~
                        postContent: ~
                    persistence:
                        driver: orm
                        model: Shop\Bundle\ManagementBundle\Entity\Post
                        provider: ~
                        #listener: ~
                        finder: ~