mobile_management:
    resource: "@MobileManagementBundle/Resources/config/routing.yml"
    prefix:   /

shop_management:
   resource: "@ShopManagementBundle/Resources/config/routing.yml"
   prefix:   /

members_management:
    resource: "@MembersManagementBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"    

