Shop\Bundle\ManagementBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
    manyToMany:
        posts:
            mappedBy: categories
            targetEntity: Shop\Bundle\ManagementBundle\Entity\Post
    
    lifecycleCallbacks: {  }


