<?php

namespace Members\Bundle\ManagementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
   
 public function getCategories()
{
    return $this->getEntityManager()
        ->createQuery('SELECT u FROM AcmeAppBundle:Category u WHERE u.parent is NULL ORDER BY u.priority DESC')
        ->getResult();
}

public function getOrderedCategories()
{
   //get the Parent-"Nodes"
   $entity = $this->getCategories();
   $arr = array();

    foreach ($entity as $cat) {  

        $arr[]=$cat;  

        foreach ($cat->getChildren() as $child)
        { 
           $arr[] = $child;
        }
    }
    
}

        }
