Members\Bundle\ManagementBundle\Entity\Follow:
    type: entity
    table: follow
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        lastDate:
            type: datetime
            column: last_date
            nullable: true
        followSeen:
            type: boolean
            column: follow_seen
            nullable: true
    manyToOne:
      follower:
        targetEntity: Members\Bundle\ManagementBundle\Entity\User
        joinColumn:
          name: follower_id
          type: integer
          referencedColumnName: id
          onDelete: cascade
      followed:
        targetEntity: Members\Bundle\ManagementBundle\Entity\User
        joinColumn:
          name: followed_id
          type: integer
          referencedColumnName: id
          onDelete: cascade
    lifecycleCallbacks: {  }
