Members\Bundle\ManagementBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        domain_name:
            type: string
            length: 30
            column: domain_name
            nullable: true
        latitude:
            type: float
            column: latitude
            nullable: true
        longitude:
            type: float
            column: longitude
            nullable: true
        store_description:
            type: text
            column: store_description
            nullable: true
        phone_number:
            type: string
            column: phone_number
            nullable: true
        createdAt:
            type: datetime
            column: created_at
            nullable: true
    oneToMany:
      posts:
        mappedBy: user
        targetEntity: Shop\Bundle\ManagementBundle\Entity\Post
        cascade:      [persist]
    oneToOne:
      profile_picture:
        targetEntity: Members\Bundle\ManagementBundle\Entity\ProfilePhoto
        joinColumn:
          name: profile_picture
          type: integer
          referencedColumnName: id
    lifecycleCallbacks: {  }