<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.repository_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManager.php';

$this->services['fos_elastica.repository_manager'] = $instance = new \FOS\ElasticaBundle\Manager\RepositoryManager();

$instance->addType('search/post', ${($_ = isset($this->services['fos_elastica.finder.search.post']) ? $this->services['fos_elastica.finder.search.post'] : $this->load('getFosElastica_Finder_Search_PostService.php')) && false ?: '_'});

return $instance;
