<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.manager.orm' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Manager/RepositoryManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RepositoryManager.php';

$this->services['fos_elastica.manager.orm'] = $instance = new \FOS\ElasticaBundle\Doctrine\RepositoryManager(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, ${($_ = isset($this->services['fos_elastica.repository_manager']) ? $this->services['fos_elastica.repository_manager'] : $this->load('getFosElastica_RepositoryManagerService.php')) && false ?: '_'});

$instance->addEntity('Shop\\Bundle\\ManagementBundle\\Entity\\Post', 'search/post');

return $instance;
