<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.persister_registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Persister/PersisterRegistry.php';

$this->services['fos_elastica.persister_registry'] = $instance = new \FOS\ElasticaBundle\Persister\PersisterRegistry(array('search' => array('post' => 'fos_elastica.object_persister.search.post')));

$instance->setContainer($this);

return $instance;
