<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.populate_listener' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/EventListener/PopulateListener.php';

return $this->services['fos_elastica.populate_listener'] = new \FOS\ElasticaBundle\EventListener\PopulateListener(${($_ = isset($this->services['fos_elastica.resetter']) ? $this->services['fos_elastica.resetter'] : $this->load('getFosElastica_ResetterService.php')) && false ?: '_'});
