<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.finder.search.post' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/ElasticaToModelTransformerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Transformer/AbstractElasticaToModelTransformer.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/AbstractElasticaToModelTransformer.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/ORM/ElasticaToModelTransformer.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Finder/FinderInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Finder/PaginatedFinderInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Finder/TransformedFinder.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php';

$a = new \FOS\ElasticaBundle\Doctrine\ORM\ElasticaToModelTransformer(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, 'Shop\\Bundle\\ManagementBundle\\Entity\\Post', array('hints' => array(), 'hydrate' => true, 'ignore_missing' => false, 'query_builder_method' => 'createQueryBuilder', 'identifier' => 'id'));
$a->setPropertyAccessor(${($_ = isset($this->services['fos_elastica.property_accessor']) ? $this->services['fos_elastica.property_accessor'] : $this->services['fos_elastica.property_accessor'] = new \Symfony\Component\PropertyAccess\PropertyAccessor(false, false)) && false ?: '_'});

return $this->services['fos_elastica.finder.search.post'] = new \FOS\ElasticaBundle\Finder\TransformedFinder(${($_ = isset($this->services['fos_elastica.index.search.post']) ? $this->services['fos_elastica.index.search.post'] : $this->load('getFosElastica_Index_Search_PostService.php')) && false ?: '_'}, $a);
