<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.command.search' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Command/SearchCommand.php';

$this->services['fos_elastica.command.search'] = $instance = new \FOS\ElasticaBundle\Command\SearchCommand(${($_ = isset($this->services['fos_elastica.index_manager']) ? $this->services['fos_elastica.index_manager'] : $this->load('getFosElastica_IndexManagerService.php')) && false ?: '_'});

$instance->setName('fos:elastica:search');

return $instance;
