<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.pager_provider.search.post' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/RegisterListenersService.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Provider/PagerProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Doctrine/ORMPagerProvider.php';

return $this->services['fos_elastica.pager_provider.search.post'] = new \FOS\ElasticaBundle\Doctrine\ORMPagerProvider(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, new \FOS\ElasticaBundle\Doctrine\RegisterListenersService(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}), 'Shop\\Bundle\\ManagementBundle\\Entity\\Post', array('batch_size' => 100, 'clear_object_manager' => true, 'debug_logging' => true, 'query_builder_method' => 'createQueryBuilder'));
