<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_elastica.command.populate' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Command/PopulateCommand.php';

$this->services['fos_elastica.command.populate'] = $instance = new \FOS\ElasticaBundle\Command\PopulateCommand(${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : $this->getDebug_EventDispatcherService()) && false ?: '_'}, ${($_ = isset($this->services['fos_elastica.index_manager']) ? $this->services['fos_elastica.index_manager'] : $this->load('getFosElastica_IndexManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_elastica.pager_provider_registry']) ? $this->services['fos_elastica.pager_provider_registry'] : $this->load('getFosElastica_PagerProviderRegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_elastica.pager_persister_registry']) ? $this->services['fos_elastica.pager_persister_registry'] : $this->load('getFosElastica_PagerPersisterRegistryService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_elastica.resetter']) ? $this->services['fos_elastica.resetter'] : $this->load('getFosElastica_ResetterService.php')) && false ?: '_'});

$instance->setName('fos:elastica:populate');

return $instance;
