<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.config_manager' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/Source/SourceInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/Source/ContainerSource.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/ManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Configuration/ConfigManager.php';

return $this->services['fos_elastica.config_manager'] = new \FOS\ElasticaBundle\Configuration\ConfigManager(array(0 => new \FOS\ElasticaBundle\Configuration\Source\ContainerSource(array('search' => array('elasticsearch_name' => 'search', 'reference' => ${($_ = isset($this->services['fos_elastica.index.search']) ? $this->services['fos_elastica.index.search'] : $this->load('getFosElastica_Index_SearchService.php')) && false ?: '_'}, 'name' => 'search', 'settings' => array(), 'type_prototype' => array(), 'use_alias' => false, 'types' => array('post' => array('name' => 'post', 'mapping' => array('dynamic_templates' => array(), 'properties' => array('postTitle' => array(), 'postContent' => array())), 'config' => array('persistence' => array('driver' => 'orm', 'model' => 'Shop\\Bundle\\ManagementBundle\\Entity\\Post', 'provider' => array('batch_size' => 100, 'clear_object_manager' => true, 'debug_logging' => true, 'query_builder_method' => 'createQueryBuilder'), 'finder' => array(), 'identifier' => 'id', 'listener' => array('enabled' => true, 'insert' => true, 'update' => true, 'delete' => true, 'flush' => true, 'defer' => false, 'logger' => false), 'elastica_to_model_transformer' => array('hints' => array(), 'hydrate' => true, 'ignore_missing' => false, 'query_builder_method' => 'createQueryBuilder'), 'model_to_elastica_transformer' => array(), 'persister' => array()), 'serializer' => array('groups' => array(), 'serialize_null' => false), 'analyzer' => NULL, 'search_analyzer' => NULL, 'dynamic' => NULL, 'date_detection' => NULL, 'dynamic_date_formats' => array(), 'numeric_detection' => NULL))))))));
