<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.index.search.post' shared service.

include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/SearchableInterface.php';
include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/Type.php';

return $this->services['fos_elastica.index.search.post'] = ${($_ = isset($this->services['fos_elastica.index.search']) ? $this->services['fos_elastica.index.search'] : $this->load('getFosElastica_Index_SearchService.php')) && false ?: '_'}->getType('post');
