<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_elastica.client.default' shared service.

include_once $this->targetDirs[3].'/vendor/ruflin/elastica/lib/Elastica/Client.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/elastica-bundle/src/Elastica/Client.php';

$this->services['fos_elastica.client.default'] = $instance = new \FOS\ElasticaBundle\Elastica\Client(array('connections' => array(0 => array('host' => 'localhost', 'port' => 9200, 'ssl' => false, 'logger' => 'fos_elastica.logger', 'compression' => false, 'headers' => array(), 'curl' => array(), 'retryOnConflict' => 0)), 'connectionStrategy' => 'Simple'), '');

$instance->setStopwatch(${($_ = isset($this->services['debug.stopwatch']) ? $this->services['debug.stopwatch'] : $this->services['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)) && false ?: '_'});
$instance->setLogger(${($_ = isset($this->services['fos_elastica.logger']) ? $this->services['fos_elastica.logger'] : $this->getFosElastica_LoggerService()) && false ?: '_'});

return $instance;
