<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'members_management.follow.services' shared service.

include_once $this->targetDirs[3].'/src/Members/Bundle/ManagementBundle/Entity/FollowServices.php';

return $this->services['members_management.follow.services'] = new \Members\Bundle\ManagementBundle\Entity\FollowServices(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
