<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'mobile_management.menu.notification' shared service.

include_once $this->targetDirs[3].'/src/Mobile/Bundle/ManagementBundle/Service/MenuNotifications.php';

return $this->services['mobile_management.menu.notification'] = new \Mobile\Bundle\ManagementBundle\Service\MenuNotifications(${($_ = isset($this->services['members_management.messages.services']) ? $this->services['members_management.messages.services'] : $this->load('getMembersManagement_Messages_ServicesService.php')) && false ?: '_'}, ${($_ = isset($this->services['members_management.follow.services']) ? $this->services['members_management.follow.services'] : $this->load('getMembersManagement_Follow_ServicesService.php')) && false ?: '_'}, ${($_ = isset($this->services['shop_management.mymarket.services']) ? $this->services['shop_management.mymarket.services'] : $this->load('getShopManagement_Mymarket_ServicesService.php')) && false ?: '_'});
