<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'shop_management.post.handler' shared service.

return $this->services['shop_management.post.handler'] = new \Shop\Bundle\ManagementBundle\Handler\PostHandler(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, 'Shop\\Bundle\\ManagementBundle\\Entity\\Post');
