<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'shop_management.image.services' shared service.

include_once $this->targetDirs[3].'/src/Shop/Bundle/ManagementBundle/Entity/ImageServices.php';

return $this->services['shop_management.image.services'] = new \Shop\Bundle\ManagementBundle\Entity\ImageServices(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
