<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'shop_management.article.paginator' shared service.

return $this->services['shop_management.article.paginator'] = new \Shop\Bundle\ManagementBundle\Handler\Paginator(${($_ = isset($this->services['my_shop_controller']) ? $this->services['my_shop_controller'] : $this->load('getMyShopControllerService.php')) && false ?: '_'});
