<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0oovj2a\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0oovj2a/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0oovj2a.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0oovj2a\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0oovj2a\appDevDebugProjectContainer(array(
    'container.build_hash' => '0oovj2a',
    'container.build_id' => 'fb62863e',
    'container.build_time' => 1523464091,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0oovj2a');
