<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtukdal\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtukdal/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXtukdal.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXtukdal\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXtukdal\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xtukdal',
    'container.build_id' => '757356e1',
    'container.build_time' => 1523472053,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtukdal');
